// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sxgdjoelhxhnegwvvmvk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN4Z2Rqb2VsaHhobmVnd3Z2bXZrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM5MTkxNzcsImV4cCI6MjA1OTQ5NTE3N30.8Jwy5HU-LodjI-1smJ_j0fVhw5BRt5iLsyylUJXTr2U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);