// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lhwljjaxgzclwhzemmdc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imxod2xqamF4Z3pjbHdoemVtbWRjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ4NzQwMjgsImV4cCI6MjA2MDQ1MDAyOH0.2fuzEPTQRy51Jxc9Pn0UGuij1TnQzuOVWh8W9p0cnA8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);